/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author solan
 */
public class WithdrawCash extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawCash
     */
    public WithdrawCash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        accBtn = new javax.swing.JButton();
        savBtn = new javax.swing.JButton();
        back5Btn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("SELECT ACCOUNT TYPE TO BE PROCESSED......");

        accBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accBtn.setText("CURRENT ACCOUNT");
        accBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accBtnActionPerformed(evt);
            }
        });

        savBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        savBtn.setText("SAVINGS ACCOUNT");
        savBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savBtnActionPerformed(evt);
            }
        });

        back5Btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back5Btn.setText("BACK");
        back5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back5BtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        mainBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mainBtn.setText("MAIN MENU");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" SJSJ BANK             ATM Loc: Dewas            Greetings!!!     ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back5Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(mainBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(savBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(accBtn)
                .addGap(45, 45, 45)
                .addComponent(savBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back5Btn)
                    .addComponent(exitBtn)
                    .addComponent(mainBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
System.exit(0);          // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
Fourth f=new Fourth();
f.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_mainBtnActionPerformed

    private void accBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accBtnActionPerformed
/*new Last().setVisible(true);
this.setVisible(false);
        */
        
        if(Third.withfiveBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>500;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-500 where pin = '"+p+"';");
            }
                else 
            {
                
               JOptionPane.showMessageDialog(null, "Insufficient Balance!!");
               
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
        
        else if(Third.withsixBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>600;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-600 where pin = '"+p+"';");
            }
                else 
            {
                
               JOptionPane.showMessageDialog(null, "Insufficient Balance!!");
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        else if(Third.withtenBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>1000;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-1000 where pin = '"+p+"';");
            }
                else 
            {
                JOptionPane.showMessageDialog(null, "Insufficient Balance!!");
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_accBtnActionPerformed

    private void savBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savBtnActionPerformed
/*new Last().setVisible(true);
this.setVisible(false); */      
        
 if(Third.withfiveBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>500;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-500 where pin = '"+p+"';");
            }
                else 
            {
                //JOptionPane.showMessageDialog(null, "Insufficient Balance!!");
                new LastOne().setVisible(true);
                this.setVisible(false);
                LastOne.failLabel.setText("Transaction Failed!!");
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
        
        else if(Third.withsixBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>600;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-600 where pin = '"+p+"';");
            }
                else 
            {
                new LastOne().setVisible(true);
                this.setVisible(false);
                LastOne.failLabel.setText("Transaction Failed!!");
             //JOptionPane.showMessageDialog(null, "Insufficient Balance!!");
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        else if(Third.withtenBtn.isSelected()==false)
        { 
       try {  
          
            String p=new String(Pin.pwdPf.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sjsjbank","root","jiya");
            Statement smt=con.createStatement(); 
            ResultSet rs = smt.executeQuery("select * from testacc where pin = '"+p+"' and AccBalance>1000;");
            if(rs.next()) 
            { 
                
                    new Last().setVisible(true);
                    this.setVisible(false);  
                    Last.trcsLabel.setText("Transaction Successfully Completed!!");
                    smt.executeUpdate("update testacc set AccBalance=AccBalance-1000 where pin = '"+p+"';");
            }
                else 
            {
               //JOptionPane.showMessageDialog(null, "Insufficient Balance!!"); 
                new LastOne().setVisible(true);
                this.setVisible(false);
                LastOne.failLabel.setText("Transaction Failed!!");
            }
            
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }


// TODO add your handling code here:
    }//GEN-LAST:event_savBtnActionPerformed

    private void back5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back5BtnActionPerformed
Third t=new Third();
t.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_back5BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton accBtn;
    private javax.swing.JButton back5Btn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainBtn;
    public static javax.swing.JButton savBtn;
    // End of variables declaration//GEN-END:variables
}
